# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# QUERY.py
# Created on: 2016-04-22 20:41:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: QUERY <INT_FIRE_TAP20KM_Layer__2_> <DATA_HOTSPOT_TAP_kmz> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Script arguments
INT_FIRE_TAP20KM_Layer__2_ = arcpy.GetParameterAsText(0)
if INT_FIRE_TAP20KM_Layer__2_ == '#' or not INT_FIRE_TAP20KM_Layer__2_:
    INT_FIRE_TAP20KM_Layer__2_ = "INT_FIRE_TAP20KM_Layer" # provide a default value if unspecified

DATA_HOTSPOT_TAP_kmz = arcpy.GetParameterAsText(1)
if DATA_HOTSPOT_TAP_kmz == '#' or not DATA_HOTSPOT_TAP_kmz:
    DATA_HOTSPOT_TAP_kmz = "S:\\DATA_HOTSPOT_TAP.kmz" # provide a default value if unspecified

# Local variables:
MODIS_C6_SouthEast_Asia_24h_shp = "T:\\MODIS_C6_SouthEast_Asia_24h.shp"
ALL_HGU_ILOK_BUFFER10KM_shp = "X:\\02_EWS_GIS\\HGU ILOK TAP\\ALL_HGU_ILOK_BUFFER10KM.shp"
ALL_HGU_ILOK_shp = "X:\\02_EWS_GIS\\HGU ILOK TAP\\ALL_HGU_ILOK.shp"
v02_EWS_GIS__2_ = "X:\\02_EWS_GIS"
FIRE_lyr = "X:\\02_EWS_GIS\\STYLE\\FIRE.lyr"
VNP14IMGT_NRT_SouthEast_Asia_24h_shp = "T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp"
v02_EWS_GIS = "X:\\02_EWS_GIS"
MODIS_C6_SouthEast_Asia_24h_shp__2_ = "X:\\02_EWS_GIS\\MODIS_C6_SouthEast_Asia_24h.shp"
INT_FIRE_TAP20KM_shp = "X:\\02_EWS_GIS\\INTERSECT_HGU_ILOK_BUFFER\\INT_FIRE_TAP20KM.shp"
INT_FIRE_TAP20KM_shp__4_ = "X:\\02_EWS_GIS\\INTERSECT_HGU_ILOK_BUFFER\\INT_FIRE_TAP20KM.shp"
INT_FIRE_TAP20KM_shp__2_ = "X:\\02_EWS_GIS\\INTERSECT_HGU_ILOK_BUFFER\\INT_FIRE_TAP20KM.shp"
INT_FIRE_TAP20KM_Layer = "INT_FIRE_TAP20KM_Layer"
VNP14IMGT_NRT_SouthEast_Asia_24h_shp__2_ = "X:\\02_EWS_GIS\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp"
VNP14IMGT_NRT_SouthEast_Asia_24h_shp__3_ = "X:\\02_EWS_GIS\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp"

# Process: Feature Class to Feature Class
arcpy.FeatureClassToFeatureClass_conversion(MODIS_C6_SouthEast_Asia_24h_shp, v02_EWS_GIS__2_, "MODIS_C6_SouthEast_Asia_24h.shp", "", "LATITUDE \"LATITUDE\" true true false 32 Double 10 31 ,First,#,T:\\MODIS_C6_SouthEast_Asia_24h.shp,LATITUDE,-1,-1;LONGITUDE \"LONGITUDE\" true true false 32 Double 10 31 ,First,#,T:\\MODIS_C6_SouthEast_Asia_24h.shp,LONGITUDE,-1,-1;BRIGHTNESS \"BRIGHTNESS\" true true false 32 Double 10 31 ,First,#,T:\\MODIS_C6_SouthEast_Asia_24h.shp,BRIGHTNESS,-1,-1;SCAN \"SCAN\" true true false 32 Double 10 31 ,First,#,T:\\MODIS_C6_SouthEast_Asia_24h.shp,SCAN,-1,-1;TRACK \"TRACK\" true true false 32 Double 10 31 ,First,#,T:\\MODIS_C6_SouthEast_Asia_24h.shp,TRACK,-1,-1;ACQ_DATE \"ACQ_DATE\" true true false 8 Date 0 0 ,First,#,T:\\MODIS_C6_SouthEast_Asia_24h.shp,ACQ_DATE,-1,-1;ACQ_TIME \"ACQ_TIME\" true true false 4 Text 0 0 ,First,#,T:\\MODIS_C6_SouthEast_Asia_24h.shp,ACQ_TIME,-1,-1;SATELLITE \"SATELLITE\" true true false 1 Text 0 0 ,First,#,T:\\MODIS_C6_SouthEast_Asia_24h.shp,SATELLITE,-1,-1;CONFIDENCE \"CONFIDENCE\" true true false 6 Long 0 6 ,First,#,T:\\MODIS_C6_SouthEast_Asia_24h.shp,CONFIDENCE,-1,-1;VERSION \"VERSION\" true true false 6 Text 0 0 ,First,#,T:\\MODIS_C6_SouthEast_Asia_24h.shp,VERSION,-1,-1;BRIGHT_T31 \"BRIGHT_T31\" true true false 32 Double 10 31 ,First,#,T:\\MODIS_C6_SouthEast_Asia_24h.shp,BRIGHT_T31,-1,-1;FRP \"FRP\" true true false 32 Double 10 31 ,First,#,T:\\MODIS_C6_SouthEast_Asia_24h.shp,FRP,-1,-1;DAYNIGHT \"DAYNIGHT\" true true false 1 Text 0 0 ,First,#,T:\\MODIS_C6_SouthEast_Asia_24h.shp,DAYNIGHT,-1,-1", "")

# Process: Define Projection
arcpy.DefineProjection_management(MODIS_C6_SouthEast_Asia_24h_shp__2_, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

# Process: Feature Class to Feature Class (2)
arcpy.FeatureClassToFeatureClass_conversion(VNP14IMGT_NRT_SouthEast_Asia_24h_shp, v02_EWS_GIS, "VNP14IMGT_NRT_SouthEast_Asia_24h.shp", "", "LATITUDE \"LATITUDE\" true true false 32 Double 10 31 ,First,#,T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp,LATITUDE,-1,-1;LONGITUDE \"LONGITUDE\" true true false 32 Double 10 31 ,First,#,T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp,LONGITUDE,-1,-1;BRIGHT_TI4 \"BRIGHT_TI4\" true true false 32 Double 10 31 ,First,#,T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp,BRIGHT_TI4,-1,-1;SCAN \"SCAN\" true true false 32 Double 10 31 ,First,#,T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp,SCAN,-1,-1;TRACK \"TRACK\" true true false 32 Double 10 31 ,First,#,T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp,TRACK,-1,-1;ACQ_DATE \"ACQ_DATE\" true true false 8 Date 0 0 ,First,#,T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp,ACQ_DATE,-1,-1;ACQ_TIME \"ACQ_TIME\" true true false 4 Text 0 0 ,First,#,T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp,ACQ_TIME,-1,-1;SATELLITE \"SATELLITE\" true true false 1 Text 0 0 ,First,#,T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp,SATELLITE,-1,-1;CONFIDENCE \"CONFIDENCE\" true true false 7 Text 0 0 ,First,#,T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp,CONFIDENCE,-1,-1;VERSION \"VERSION\" true true false 6 Text 0 0 ,First,#,T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp,VERSION,-1,-1;BRIGHT_TI5 \"BRIGHT_TI5\" true true false 32 Double 10 31 ,First,#,T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp,BRIGHT_TI5,-1,-1;FRP \"FRP\" true true false 32 Double 10 31 ,First,#,T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp,FRP,-1,-1;DAYNIGHT \"DAYNIGHT\" true true false 1 Text 0 0 ,First,#,T:\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp,DAYNIGHT,-1,-1", "")

# Process: Define Projection (2)
arcpy.DefineProjection_management(VNP14IMGT_NRT_SouthEast_Asia_24h_shp__2_, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

# Process: Append (2)
arcpy.Append_management("X:\\02_EWS_GIS\\MODIS_C6_SouthEast_Asia_24h.shp", VNP14IMGT_NRT_SouthEast_Asia_24h_shp__3_, "NO_TEST", "LATITUDE \"LATITUDE\" true true false 32 Double 10 31 ,First,#,X:\\02_EWS_GIS\\MODIS_C6_SouthEast_Asia_24h.shp,LATITUDE,-1,-1;LONGITUDE \"LONGITUDE\" true true false 32 Double 10 31 ,First,#,X:\\02_EWS_GIS\\MODIS_C6_SouthEast_Asia_24h.shp,LONGITUDE,-1,-1;BRIGHT_TI4 \"BRIGHT_TI4\" true true false 32 Double 10 31 ,First,#;SCAN \"SCAN\" true true false 32 Double 10 31 ,First,#,X:\\02_EWS_GIS\\MODIS_C6_SouthEast_Asia_24h.shp,SCAN,-1,-1;TRACK \"TRACK\" true true false 32 Double 10 31 ,First,#,X:\\02_EWS_GIS\\MODIS_C6_SouthEast_Asia_24h.shp,TRACK,-1,-1;ACQ_DATE \"ACQ_DATE\" true true false 8 Date 0 0 ,First,#,X:\\02_EWS_GIS\\MODIS_C6_SouthEast_Asia_24h.shp,ACQ_DATE,-1,-1;ACQ_TIME \"ACQ_TIME\" true true false 4 Text 0 0 ,First,#,X:\\02_EWS_GIS\\MODIS_C6_SouthEast_Asia_24h.shp,ACQ_TIME,-1,-1;SATELLITE \"SATELLITE\" true true false 1 Text 0 0 ,First,#,X:\\02_EWS_GIS\\MODIS_C6_SouthEast_Asia_24h.shp,SATELLITE,-1,-1;CONFIDENCE \"CONFIDENCE\" true true false 7 Text 0 0 ,First,#,X:\\02_EWS_GIS\\MODIS_C6_SouthEast_Asia_24h.shp,CONFIDENCE,-1,-1;VERSION \"VERSION\" true true false 6 Text 0 0 ,First,#,X:\\02_EWS_GIS\\MODIS_C6_SouthEast_Asia_24h.shp,VERSION,-1,-1;BRIGHT_TI5 \"BRIGHT_TI5\" true true false 32 Double 10 31 ,First,#;FRP \"FRP\" true true false 32 Double 10 31 ,First,#,X:\\02_EWS_GIS\\MODIS_C6_SouthEast_Asia_24h.shp,FRP,-1,-1;DAYNIGHT \"DAYNIGHT\" true true false 1 Text 0 0 ,First,#,X:\\02_EWS_GIS\\MODIS_C6_SouthEast_Asia_24h.shp,DAYNIGHT,-1,-1", "")

# Process: Intersect
arcpy.Intersect_analysis("'X:\\02_EWS_GIS\\HGU ILOK TAP\\ALL_HGU_ILOK_BUFFER10KM.shp' #;X:\\02_EWS_GIS\\VNP14IMGT_NRT_SouthEast_Asia_24h.shp #", INT_FIRE_TAP20KM_shp, "NO_FID", "", "INPUT")

# Process: Near
arcpy.Near_analysis(INT_FIRE_TAP20KM_shp, "'X:\\02_EWS_GIS\\HGU ILOK TAP\\ALL_HGU_ILOK.shp'", "20 Kilometers", "NO_LOCATION", "NO_ANGLE")

# Process: Calculate Field
arcpy.CalculateField_management(INT_FIRE_TAP20KM_shp__4_, "NEAR_DIST", "[NEAR_DIST] *111.11", "VB", "")

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(INT_FIRE_TAP20KM_shp__2_, INT_FIRE_TAP20KM_Layer, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;COMP_NAME COMP_NAME VISIBLE NONE;COMP_CODE COMP_CODE VISIBLE NONE;LATITUDE LATITUDE VISIBLE NONE;LONGITUDE LONGITUDE VISIBLE NONE;BRIGHT_TI4 BRIGHT_TI4 VISIBLE NONE;SCAN SCAN VISIBLE NONE;TRACK TRACK VISIBLE NONE;ACQ_DATE ACQ_DATE VISIBLE NONE;ACQ_TIME ACQ_TIME VISIBLE NONE;SATELLITE SATELLITE VISIBLE NONE;CONFIDENCE CONFIDENCE VISIBLE NONE;VERSION VERSION VISIBLE NONE;BRIGHT_TI5 BRIGHT_TI5 VISIBLE NONE;FRP FRP VISIBLE NONE;DAYNIGHT DAYNIGHT VISIBLE NONE;NEAR_FID NEAR_FID VISIBLE NONE;NEAR_DIST NEAR_DIST VISIBLE NONE")

# Process: Apply Symbology From Layer
arcpy.ApplySymbologyFromLayer_management(INT_FIRE_TAP20KM_Layer, FIRE_lyr)

# Process: Layer To KML
arcpy.LayerToKML_conversion(INT_FIRE_TAP20KM_Layer__2_, DATA_HOTSPOT_TAP_kmz, "0", "false", "DEFAULT", "1024", "96", "CLAMPED_TO_GROUND")

