# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# QUERY_DATABASE.py
# Created on: 2016-04-22 20:42:27.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("X:/02_EWS_GIS/TOOLS/Excel_and_CSV_Conversion_Tools/ExcelTools/Excel and CSV Conversion Tools.tbx")


# Local variables:
INT_FIRE_TAP20KM_shp = "X:\\02_EWS_GIS\\INTERSECT_HGU_ILOK_BUFFER\\INT_FIRE_TAP20KM.shp"
POINT_HOTSPOT = "X:\\02_EWS_GIS\\DATABASE_FIREHOTSPOT_TAP.gdb\\POINT_HOTSPOT_NASA\\POINT_HOTSPOT"
DATA_HOTSPOT_TAP_csv = "U:\\DATA HOTSPOT TAP.csv"

# Process: TableToCSV
arcpy.TableToCSV_tableconversion(INT_FIRE_TAP20KM_shp, DATA_HOTSPOT_TAP_csv, "COMMA")

# Process: Append
arcpy.Append_management("X:\\02_EWS_GIS\\INTERSECT_HGU_ILOK_BUFFER\\INT_FIRE_TAP20KM.shp", POINT_HOTSPOT, "NO_TEST", "LATITUDE \"LATITUDE\" true false false 8 Double 0 0 ,First,#;LONGITUDE \"LONGITUDE\" true false false 8 Double 0 0 ,First,#;BRIGHT_TI4 \"BRIGHT_TI4\" true false false 8 Double 0 0 ,First,#;SCAN \"SCAN\" true false false 8 Double 0 0 ,First,#;TRACK \"TRACK\" true false false 8 Double 0 0 ,First,#;ACQ_DATE \"ACQ_DATE\" true true false 8 Date 0 0 ,First,#;ACQ_TIME \"ACQ_TIME\" true false false 4 Text 0 0 ,First,#;SATELLITE \"SATELLITE\" true false false 1 Text 0 0 ,First,#;CONFIDENCE \"CONFIDENCE\" true false false 7 Text 0 0 ,First,#;VERSION \"VERSION\" true false false 6 Text 0 0 ,First,#;BRIGHT_TI5 \"BRIGHT_TI5\" true false false 8 Double 0 0 ,First,#;FRP \"FRP\" true false false 8 Double 0 0 ,First,#;DAYNIGHT \"DAYNIGHT\" true false false 1 Text 0 0 ,First,#", "")

